Algoritmo "notas"

Var

   nota1, nota2, notaMedia : real


Inicio

   escreva("Digite nota Primeiro Semestre: ")
   leia(nota1)
   escreva("Digite nota Segundo Semestre: ")
   leia(nota2)
   notaMedia <- nota1 + nota2
   
   se notaMedia < 60 entao
      escreval("NOTA FINAL = ", notamedia:3:1)
      escreval("Voce foi REPROVADO")
   senao
      escreval("NOTA FINAL = ", notamedia:3:1)
      escreval("Voce foi APROVADA")
   fimse
   




Fimalgoritmo
